### ISSUE TITLE
Error when compile

### ISSUE THREAD

**Issue by liming0791** [rubengooj/StVO-PL#1]
when compile the project, I got this error message:

> /home/liming/opencv3/include/opencv2/line_descriptor/descriptor.hpp:431:9: error: ‘class cv::line_descriptor::BinaryDescriptor::EDLineDetector’ is private
   class EDLineDetector
         ^
/home/liming/Projects/StVO-PL/src/stereoFrame.cpp:535:31: error: within this context
             BinaryDescriptor::EDLineDetector* edl = new BinaryDescriptor::EDLineDetector(opts);
                                                                                                                   ^
/home/liming/opencv3/include/opencv2/line_descriptor/descriptor.hpp:408:10: error: ‘struct cv::line_descriptor::BinaryDescriptor::EDLineParam’ is private
   struct EDLineParam
          ^
/home/liming/Projects/StVO-PL/src/stereoFrame.cpp:527:31: error: within this context
             BinaryDescriptor::EDLineParam opts;
                               ^

Besides, I use opencv 3.0.0 .

**Comment by liming0791** [comment]
I have not seen the modified 3rdparty files, sorry ...

**Comment by RichardChe** [comment]
@liming0791 Did you succeeded with the modified 3rdparty files?

I used the files in the 3rdparty but it still failed in linking, with the following error information:

../lib/libstvo.so: undefined reference to `cv::line_descriptor::LSDDetector::detect(cv::Mat const&, std::vector<cv::line_descriptor::KeyLine, std::allocator<cv::line_descriptor::KeyLine> >&, int, int, cv::line_descriptor::LSDDetector::LSDOptions, cv::Mat const&)'
collect2: error: ld returned 1 exit status
make[2]: *** [imagesStVO] Error 1
make[1]: *** [CMakeFiles/imagesStVO.dir/all] Error 2
