### ISSUE TITLE
When I build the 3rdparty folder line_descriptor, an error occurs.

### ISSUE THREAD

**Issue by whuwan** [rubengooj/StVO-PL#4]
Hi, to use your program, I build the line_descriptor. However, an error occur. The error is:

iptor/build$ cmake ..
-- The C compiler identification is GNU 4.8.4
-- The CXX compiler identification is GNU 4.8.4
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
CMake Error at CMakeLists.txt:2 (ocv_define_module):
  Unknown CMake command "ocv_define_module".

Please help me, thank you very much!

**Comment by antithing** [comment]
Hi, I have the same issue. I think it is an opencv module, and you need to build it into opencv.

**Comment by rubengooj** [comment]
Hi, you have to copy the folder _line_descriptor_ to modules in the opencv, and then build the opencv again, as it is an extra opencv module.
Best, Rubén.
