### ISSUE TITLE
Monocular version?

### ISSUE THREAD

**Issue by antithing** [rubengooj/StVO-PL#5]
Hi, and thank you for making this code available.  Is the monocular version also open source? have you released it as well? 

Thanks again!

**Comment by rubengooj** [comment]
Hi, actually we are about to release the opens source version of our monocular odometry (actually it is not a monocular version of this one, but an extension of SVO from Forster et al. to the case of also employing line segments). Thanks!

**Comment by antithing** [comment]
Great! Thank you! :)
